server.port=8083

spring.application.name=ms-estacionamento

logging.level.org.hibernate.sql=debug
logging.level.org.hibernate.type=trace

spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=estacionamento
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=mongodb
spring.data.mongodb.password=mongodb
spring.data.mongodb.auto-initialize=true

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.topic.estacionamento.envio-de-mail=estacionamento.envio-de-mail

ms-veiculo.url.url=http://localhost:8080/veiculo
