server.port=8080

spring.application.name=ms-gateway

ms-auth.url=http://localhost:8081/auth
ms-user.url=http://localhost:8082/user
ms-vehicle.url=http://localhost:8083/vehicle
ms-parking.url=http://localhost:8084/parking
ms-parking-ticket.url=http://localhost:8085/parking-ticket

