server.port=8080

spring.application.name=ms-gateway

ms-usuario.url=http://localhost:8081/usuario
ms-veiculo.url=http://localhost:8082/veiculo
ms-estacionamento.url=http://localhost:8083/estacionamento
ms-multa.url=http://localhost:8084/multa

